version: '3.8'

services:
  client:
    build:
      context: ./Bang_FE
      dockerfile: ../client/Dockerfile
    container_name: react_client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./Bang_BE
      dockerfile: Dockerfile
    container_name: nestjs_server
    environment:
      - MONGO_URI=mongodb://mongo:27017/humanscape
    ports:
      - "8080:8080"
    depends_on:
      - mongo


  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=humanscape